version: '3.8'

services:
  similarity-app:
    build: .
    container_name: similarity-evaluation
    ports:
      - "8888:8888"
      - "8501:8501"
    volumes:
      - ./dataset:/app/dataset
      - ./reports:/app/reports
      - ./notebooks:/app/notebooks
    environment:
      - PYTHONPATH=/app
      - JUPYTER_ENABLE_LAB=yes
    command: >
      bash -c "
        python main.py &&
        jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password='' &
        streamlit run app.py --server.address=0.0.0.0 --server.port=8501
      "
    networks:
      - similarity-net

  # Streamlit web interface
  streamlit-app:
    build: .
    container_name: similarity-streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./dataset:/app/dataset
      - ./reports:/app/reports
    environment:
      - PYTHONPATH=/app
    command: streamlit run app.py --server.address=0.0.0.0 --server.port=8501
    networks:
      - similarity-net

networks:
  similarity-net:
    driver: bridge