version: '3.8'

services:

  # Streamlit web interface
  streamlit-app:
    build: .
    container_name: similarity-streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./dataset:/app/dataset
      - ./reports:/app/reports
    environment:
      - PYTHONPATH=/app
    command: streamlit run app.py --server.address=0.0.0.0 --server.port=8501
    networks:
      - similarity-net

networks:
  similarity-net:
    driver: bridge